name: Suggest an Asset
title: '[NEW ASSET] Asset Name'
description: Suggest an asset to be added to the list!
labels: 'asset suggestion'
body:

# asset name block
- type: input
  id: asset-name
  attributes:
    label: Asset Name
    description: "The name of the asset you're suggesting. Feel free to suggest more than one!"
    placeholder: "VS Code"
  validations:
    required: true

# reason to add block
- type: textarea
  id: reason
  attributes:
    label: Why?
    description: "Why we should add the asset(s) to the project."
    placeholder: "It's popular for web development..."
  validations:
    required: true

# reference image block
- type: textarea
  id: reference-image
  attributes:
    label: Reference Image
    description: "Do you have any images of what the logo looks like? SVG preferred."
    placeholder: "Feel free to drag and drop the files here."
  validations:
    required: false
